# Generated by Django 5.2 on 2025-04-18 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo_path', models.FileField(upload_to='documentos/')),
                ('extension', models.CharField(choices=[('word', 'Documento Word'), ('txt', 'Texto Plano'), ('excel', 'Hoja de Cálculo Excel'), ('cal', 'Hoja de Cálculo CAL'), ('ppt', 'Presentación PowerPoint'), ('pdf', 'Documento PDF'), ('html', 'HTML'), ('php', 'PHP'), ('css', 'Hoja de Estilos CSS'), ('js', 'JavaScript')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['titulo', 'usuario'], name='documentos__titulo_822afa_idx')],
            },
        ),
    ]
